In [1]:
import numpy as np
import pandas as pd

In [2]:
a = pd.Series([1, 2, 3])
df = pd.DataFrame(np.random.randint(50, size=50).reshape(10, 5))

Q1
Write a Pandas program to create and display a one-dimensional array-like object containing an array of data using Pandas module.

In [3]:
pd.Series([1,2,4])

0    1
1    2
2    4
dtype: int64

Q2 Write a Pandas program to convert a Panda module Series to Python list
and it's type.

In [4]:
a = pd.Series([1,2,3])
a = a.to_list()
a

[1, 2, 3]

Q3 Write a Pandas program to add, subtract, multiple and divide two Pandas
Series.

In [5]:
a = pd.Series([5,10,15])
b = pd.Series([5,5,5])

print(a+b)
print(a-b)
print(a*b)
print(a/b)

0    10
1    15
2    20
dtype: int64
0     0
1     5
2    10
dtype: int64
0    25
1    50
2    75
dtype: int64
0    1.0
1    2.0
2    3.0
dtype: float64


Q4 Write a Pandas program to compare the elements of the two Pandas
Series.

In [6]:
a = pd.Series([5,10,15])
b = pd.Series([5,5,5])

print(a == b)
print(a != b)
print(a > b)
print(a < b)
print(a)

0     True
1    False
2    False
dtype: bool
0    False
1     True
2     True
dtype: bool
0    False
1     True
2     True
dtype: bool
0    False
1    False
2    False
dtype: bool
0     5
1    10
2    15
dtype: int64


Q5 Write a Pandas program to convert a dictionary to a Pandas series.

In [7]:
d = {'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
pd.Series(d)

a    100
b    200
c    300
d    400
e    800
dtype: int64

Q6 Write a Pandas program to convert a NumPy array to a Pandas series.

In [8]:
a = np.array([1,2,3])
pd.Series(a)

0    1
1    2
2    3
dtype: int64

Q7 Write a Pandas program to change the data type of given a column or a
Series.

In [9]:
pd.Series([5,10,15]).astype('Float64')

0     5.0
1    10.0
2    15.0
dtype: Float64

Q8 Write a Pandas program to convert the first column of a DataFrame as a
Series.

In [10]:
df = pd.DataFrame(np.random.randint(50, size=50).reshape(10, 5))
df[0]

0     9
1    14
2     0
3    45
4     9
5    15
6    39
7    49
8    31
9    17
Name: 0, dtype: int64

Q9 Write a Pandas program to convert a given Series to an array.

In [11]:
pd.Series([1,2,3]).to_numpy()

array([1, 2, 3])

Q10 Write a Pandas program to convert Series of lists to one Series.

In [12]:
a = pd.Series([['Red', 'White', 'Black'], ['Red', 'White'], ['Black']])
a.explode(ignore_index=True)

0      Red
1    White
2    Black
3      Red
4    White
5    Black
dtype: object

Q11 Write a Pandas program to sort a given Series.

In [13]:
isinstance('p', str)

True

In [14]:
a = pd.Series(['#', 4000, 1000, 200, 'python', 300.12]).to_list()

def temp(ele):
    if isinstance(ele,str)!=True:
        return ele
    else:
        return np.inf
    
a.sort(key = lambda x:temp(x))
pd.Series(a)

0       200
1    300.12
2      1000
3      4000
4         #
5    python
dtype: object

Q12 Write a Pandas program to add some data to an existing Series.

In [15]:
a = pd.Series([400, 1000, 200, 'python', 300.12])
a.append(pd.Series([1]), ignore_index=True)

/tmp/ipykernel_2965/2143189570.py:2: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  a.append(pd.Series([1]), ignore_index=True)


0       400
1      1000
2       200
3    python
4    300.12
5         1
dtype: object

Q13 Write a Pandas program to create a subset of a given series based on value and
condition.

In [16]:
a = np.arange(0, 10, 1)
a[a > 5]

array([6, 7, 8, 9])

Q14 Write a Pandas program to change the order of index of a given series.

In [17]:
d = {'A': 10, 'B': 20, 'C': 30, 'D': 40}
a = pd.Series(d)
a.index = a.index[::-1].to_list()
a

D    10
C    20
B    30
A    40
dtype: int64

Q15 Write a Pandas program to create the mean and standard deviation of the data of a
given Series.

In [18]:
print(a.mean())
print(a.std())

25.0
12.909944487358056


Q16 Write a Pandas program to get the items of a given series not present in another given
series.

In [19]:
a=pd.Series([2,3,4,5,6,7])
b=pd.Series([12,4,6,10,6,7])
a[~a.isin(b)]

0    2
1    3
3    5
dtype: int64

Q17 Write a Pandas program to get the items which are not common of two given series.

In [20]:
a=pd.Series([2,3,4,5,6,7])
b=pd.Series([12,4,6,10,6,7])
pd.Series(list(set(a).symmetric_difference(set(b))))

0     2
1     3
2     5
3    10
4    12
dtype: int64

Q18 Write a Pandas program to compute the minimum, 25th percentile, median, 75th, and
maximum of a given series.

In [21]:
a = pd.Series(np.arange(1, 101, 1))
print(a.min())
print(a.max())
print(a.median())
print(a.quantile(0.25))
print(a.quantile(0.75))

1
100
50.5
25.75
75.25


Q19 Write a Pandas program to calculate the frequency counts of each unique value of a
given series.

In [22]:
a = pd.Series([1, 1, 1, 1, 2, 2, 3, 4, 5, 6, 7, 8, 1, 1, 2 ,3, 5, 2, 2, 2, 2, 2])
a.value_counts()

2    8
1    6
3    2
5    2
4    1
6    1
7    1
8    1
dtype: int64

Q20 Write a Pandas program to display most frequent value in a given series and replace
everything else as 'Other' in the series.

In [23]:
a = pd.Series([1, 1, 1, 1, 2, 2, 3, 4, 5, 6, 7, 8, 1, 1, 2 ,3, 5, 2, 2, 2, 2, 2])
most_freq = a.value_counts().index[0]
b = a[~a.isin([2])]
a.replace(b.values, 'other')

0     other
1     other
2     other
3     other
4         2
5         2
6     other
7     other
8     other
9     other
10    other
11    other
12    other
13    other
14        2
15    other
16    other
17        2
18        2
19        2
20        2
21        2
dtype: object

Q21 Write a Pandas program to find the positions of numbers that are multiples of 5 of a
given series.

In [24]:
d = pd.Series([1,5,15,10,25,34,65,78])
for idx, value in enumerate(d):
    if value%5==0:
        print(idx)

d[d%5==0].index

1
2
3
4
6


Int64Index([1, 2, 3, 4, 6], dtype='int64')

Q22 Write a Pandas program to extract items at given positions of a given series.

In [25]:
d = pd.Series([1,5,15,10,25,34,65,78])
d[[0,4,5,6]]

0     1
4    25
5    34
6    65
dtype: int64

Q23 Write a Pandas program to get the positions of items of a given series in another
given series.

In [26]:
d = pd.Series([1,5,15,10,25,34,65,78])
e = pd.Series([1,15,10,21,34,55,88])
lst = []
for ele in e:
    if ele in d.values:
        lst.append(d[d==ele].index[0])
lst

[0, 2, 3, 5]

Q24 Write a Pandas program convert the first and last character of each word to upper
case in each word of a given series.

In [27]:
d= pd.Series(['rohith','ved','raj','cheenmay'])
def func(ele):
    return ele[0].upper()+ele[1:-1]+ele[-1].upper()
d = d.map(func)
d


0      RohitH
1         VeD
2         RaJ
3    CheenmaY
dtype: object

Q25 Write a Pandas program to calculate the number of characters in each word in a given
series.

In [28]:
d = pd.Series(['rohith','ved','raj','cheenmay'])
e = d.map(lambda x: len(x) )
e

0    6
1    3
2    3
3    8
dtype: int64

Q26 Write a Pandas program to compute difference of differences between consecutive
numbers of a given series.

In [29]:
d = pd.Series([1,5,15,10,25,34,65,78])
lst=[]
lst2=[]
for i in range(len(d)-1):
    lst.append(d[i+1]-d[i])
for i in range(len(lst)-1):
    lst2.append(lst[i+1]-lst[i])
lst2

[6, -15, 20, -6, 22, -18]

Q27 Write a Pandas program to convert a series of date strings to a timeseries.

In [30]:
date_series = pd.Series(['01 Jan 2015', '10-02-2016', '20180307', '2014/05/06', '2016-04-12', '2019-04-06T11:20'])
date_series = pd.to_datetime(date_series)

Q28 Write a Pandas program to get the day of month, day of year, week number and day
of week from a given series of date strings.

In [31]:
date_series = pd.Series(['01 Jan 2015'])
date_series = pd.to_datetime(date_series)
print(date_series.dt.day_of_year)
print(date_series.dt.month)
print(date_series.dt.day_of_week)

0    1
dtype: int64
0    1
dtype: int64
0    3
dtype: int64


Q29 Write a Pandas program to convert year-month string to dates adding a specified day
of the month.

In [32]:
dt_seri = pd.Series(['jan-20','feb-19','03-18','apr-17'])

a = dt_seri.map(lambda x:'11-'+x)
a = pd.to_datetime(a)
a

0   2020-01-11
1   2019-02-11
2   2018-11-03
3   2017-04-11
dtype: datetime64[ns]

Q30 Write a Pandas program to filter words from a given series that contain atleast two
vowels.

In [33]:
d = pd.Series(['rohith','ved','raj','cheenmay'])
lst=['a','e','i','o','u']
def func(ele):
    counter = 0
    for i in ele:
        if i.lower() in lst:
            counter+=1
    if counter>=2:
        return False
    else:
        return True
pd.Series(filter(lambda x:func(x),d))

0    ved
1    raj
dtype: object

Q31 Write a Pandas program to compute the Euclidean distance between two given series.
Euclidean distance
From Wikipedia,
In mathematics, the Euclidean distance or Euclidean metric is the "ordinary" straight-line
distance between two points in Euclidean space. With this distance, Euclidean space
becomes a metric space. The associated norm is called the Euclidean norm.

In [34]:
s1 = pd.Series(np.arange(1,11))
s2 = pd.Series(np.arange(31,21,-1))
s3 = (s2-s1)**2
(s3.sum())**(1/2)

68.84765791223401

Q32 Write a Pandas program to find the positions of the values neighboured by smaller
values on both sides in a given series.

In [37]:
a = pd.Series([1, 8, 7, 5, 6, 5, 3, 4, 7, 1])
temp = np.diff(np.sign(np.diff(a)))
result = np.where(temp == -2)[0] + 1
print(result)

[1 4 8]


Q33 Write a Pandas program to replace missing white spaces in a given string with the
least frequent character.

In [44]:
test_str = 'abc def abcdef icd'

# using numpy to get count of each element in string
unique, counts = np.unique(np.array(list(test_str)), return_counts=True)
all_freq = dict(zip(unique, counts))

# Converted frequency to the series
ser = pd.Series(all_freq).sort_values(ascending=False)
ser

# Replacing the white space with least frequent in string
test_str = test_str.replace(' ', ser.index[-1])
test_str

'abcidefiabcdefiicd'

Q34 Write a Pandas program to compute the autocorrelations of a given numeric series.
From Wikipedia:
Autocorrelation, also known as serial correlation, is the correlation of a signal with a
delayed copy of itself as a function of delay. Informally, it is the similarity between
observations as a function of the time lag between them.

In [45]:
a = pd.Series([1, 8, 7, 5, 6, 5, 3, 4, 7, 1])
a.autocorr()

-0.3628571428571429

Q35 Write a Pandas program to create a TimeSeries to display all the Sundays of given
year.

In [46]:
pd.Series(pd.date_range('2022-01-01', periods=52, freq='W-SUN'))

0    2022-01-02
1    2022-01-09
2    2022-01-16
3    2022-01-23
4    2022-01-30
5    2022-02-06
6    2022-02-13
7    2022-02-20
8    2022-02-27
9    2022-03-06
10   2022-03-13
11   2022-03-20
12   2022-03-27
13   2022-04-03
14   2022-04-10
15   2022-04-17
16   2022-04-24
17   2022-05-01
18   2022-05-08
19   2022-05-15
20   2022-05-22
21   2022-05-29
22   2022-06-05
23   2022-06-12
24   2022-06-19
25   2022-06-26
26   2022-07-03
27   2022-07-10
28   2022-07-17
29   2022-07-24
30   2022-07-31
31   2022-08-07
32   2022-08-14
33   2022-08-21
34   2022-08-28
35   2022-09-04
36   2022-09-11
37   2022-09-18
38   2022-09-25
39   2022-10-02
40   2022-10-09
41   2022-10-16
42   2022-10-23
43   2022-10-30
44   2022-11-06
45   2022-11-13
46   2022-11-20
47   2022-11-27
48   2022-12-04
49   2022-12-11
50   2022-12-18
51   2022-12-25
dtype: datetime64[ns]

Q36 Write a Pandas program to convert given series into a dataframe with its index as
another column on the dataframe.

In [51]:
a = pd.Series([1, 2, 3, 4, 5], index=['A', 'B', 'C', 'D', 'E'])
a.to_frame().reset_index()

index  0
0     A  1
1     B  2
2     C  3
3     D  4
4     E  5

Q37 Write a Pandas program to convert given series into a dataframe with its index as
another column on the dataframe.

In [57]:
a = pd.Series(np.arange(10))
b = pd.Series(list('abcdefghj'))
df = pd.concat([a, b])
df1 = pd.concat([a, b], axis=1)
print(df)
print(df1)

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
0    a
1    b
2    c
3    d
4    e
5    f
6    g
7    h
8    j
dtype: object
   0    1
0  0    a
1  1    b
2  2    c
3  3    d
4  4    e
5  5    f
6  6    g
7  7    h
8  8    j
9  9  NaN


Q38 Write a Pandas program to check the equality of two given series.

In [64]:
a = pd.Series([1, 8, 7, 5, 6, 5, 3, 4, 7, 1])
b = pd.Series([1, 2, 7, 3, 4, 7, 8, 3, 7, 1])
a == b

0     True
1    False
2     True
3    False
4    False
5    False
6    False
7    False
8     True
9     True
dtype: bool

Q39 Write a Pandas program to find the index of the first occurrence of the smallest and
largest value of a given series.

In [70]:
a = pd.Series([1, 7, 3, 2, 8, 2, 4, 9, 1, 6, 0, 6, 8])
max_value = a.max()
min_value = a.min()
max_pos = a.values.tolist().index(max_value) + 1
min_pos = a.values.tolist().index(min_value) + 1
print(max_pos, min_pos)

8 11


Q40 Write a Pandas program to check inequality over the index axis of a given dataframe
and a given series.

In [75]:
df_data = pd.DataFrame({'W':[68,75,86,80,None],'X':[78,75,None,80,86], 'Y':[84,94,89,86,86],'Z':[86,97,96,72,83]});
sr_data = pd.Series([68, 75, 86, 80, None]) 
print(df_data)
print(sr_data)
df_data.ne(sr_data, axis=0)

      W     X   Y   Z
0  68.0  78.0  84  86
1  75.0  75.0  94  97
2  86.0   NaN  89  96
3  80.0  80.0  86  72
4   NaN  86.0  86  83
0    68.0
1    75.0
2    86.0
3    80.0
4     NaN
dtype: float64


W      X     Y     Z
0  False   True  True  True
1  False  False  True  True
2  False   True  True  True
3  False  False  True  True
4   True   True  True  True